#Circleci Configuration file

version: 2.1

jobs:
  build:
    docker:
    #primary docker image where all the steps will run
      - image: cimg/python:3.11.1
      # auth:
      #   username: mydockerhub-user
      #   password: $DOCKERHUB_PASSWORD
    
    steps:
      - run: echo "Say hello to Yaml"

      